use clap::{App, Arg};

pub fn clap() -> App<'static, 'static> {
    App::new(env!("CARGO_PKG_NAME"))
        .version(env!("CARGO_PKG_VERSION"))
        .author(env!("CARGO_PKG_AUTHORS"))
        .arg(Arg::with_name("google-client-id")
            .short("a")
            .long("google-client-id")
            .required(true)
            .takes_value(true))
        .arg(Arg::with_name("google-client-secret")
            .short("b")
            .long("google-client-secret")
            .required(true)
            .takes_value(true))
        .arg(Arg::with_name("spotify-client-id")
            .short("c")
            .long("spotify-client-id")
            .required(true)
            .takes_value(true))
        .arg(Arg::with_name("spotify-client-secret")
            .short("d")
            .long("spotify-client-secret")
            .required(true)
            .takes_value(true))
        .arg(Arg::with_name("playlist-url")
            .short("p")
            .long("playlist-url")
            .required(true)
            .takes_value(true))
}